name: todos

services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    env_file:
      - ./.env
    volumes:
      - ./docker/db:/var/lib/postgresql/data
    networks:
      - todos
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 2s
      timeout: 2s
      retries: 10

  redis:
    image: redis:7.0.7
    networks:
      - todos
    ports:
      - "6379:6379"

  minio-storage:
    image: minio/minio
    container_name: "minio"
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
    volumes:
      - ./docker/data/storage:/data
    networks:
      - todos
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 5s
      timeout: 5s
      retries: 10

networks:
  todos:
