# Generated by Django 5.1.5 on 2025-02-04 19:17

import app.types
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('email_verified', models.BooleanField(default=False)),
                ('image', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='Verification',
            fields=[
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('identifier', models.TextField()),
                ('value', models.TextField()),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'verifications',
            },
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('account_id', models.CharField(max_length=255)),
                ('provider_id', models.CharField(max_length=255)),
                ('access_token', models.CharField(max_length=255, null=True)),
                ('refresh_token', models.CharField(max_length=255, null=True)),
                ('access_token_expires_at', models.DateTimeField(null=True)),
                ('refresh_token_expires_at', models.DateTimeField(null=True)),
                ('scope', models.CharField(max_length=255, null=True)),
                ('id_token', models.TextField(null=True)),
                ('password', models.CharField(max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'accounts',
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('token', models.CharField(max_length=255)),
                ('expires_at', models.DateTimeField()),
                ('ip_address', models.CharField(max_length=255, null=True)),
                ('user_agent', models.CharField(max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'sessions',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(db_index=True, default=0)),
                ('title', models.CharField(max_length=128)),
                ('status', models.CharField(default=app.types.TaskStatus['PENDING'], max_length=25)),
                ('tags', models.JSONField(default=list)),
                ('description', models.TextField()),
                ('expected_date', models.DateTimeField(null=True)),
                ('deleted_at', models.DateTimeField(db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'task',
                'verbose_name_plural': 'tasks',
                'db_table': 'tasks',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('file', models.FileField(upload_to='uploads')),
                ('content_type', models.CharField(blank=True, max_length=255, null=True)),
                ('size', models.IntegerField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='medias', to='app.task')),
            ],
            options={
                'db_table': 'medias',
            },
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['status', 'order', 'deleted_at'], name='tasks_status_8fee15_idx'),
        ),
    ]
