# Generated by Django 5.1.5 on 2025-02-07 15:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.task'),
        ),
    ]
